package com.jik.core.designsystem.theme

import androidx.compose.ui.graphics.Color

object IconColor {
    val Star = Color(0xFFFFC72F)
}

internal val md_theme_light_primary = Color(0xFFE21111)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFFFdad5)
internal val md_theme_light_onPrimaryContainer = Color(0xFF410001)
internal val md_theme_light_secondary = Color(0xFF775652)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFFFdad5)
internal val md_theme_light_onSecondaryContainer = Color(0xFF2c1512)
internal val md_theme_light_tertiary = Color(0xFF745470)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFFFD6F8)
internal val md_theme_light_onTertiaryContainer = Color(0xFF2B122A)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFFFFFFF)
internal val md_theme_light_onBackground = Color(0xFF000000)
internal val md_theme_light_surface = Color(0xFFFEFBFF)
internal val md_theme_light_onSurface = Color(0xFF1B1B1F)
internal val md_theme_light_surfaceVariant = Color(0xFFE2E2EC)
internal val md_theme_light_onSurfaceVariant = Color(0xFF45464F)
internal val md_theme_light_outline = Color(0xFF757680)

internal val md_theme_dark_primary = Color(0xFFE21111)
internal val md_theme_dark_onPrimary = Color(0xFF000000)
internal val md_theme_dark_primaryContainer = Color(0xFF930004)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFffdad5)
internal val md_theme_dark_secondary = Color(0xFFe7bdb7)
internal val md_theme_dark_onSecondary = Color(0xFF442926)
internal val md_theme_dark_secondaryContainer = Color(0xFF5d3f3b)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFffdad5)
internal val md_theme_dark_tertiary = Color(0xFFE2BBDB)
internal val md_theme_dark_onTertiary = Color(0xFF422740)
internal val md_theme_dark_tertiaryContainer = Color(0xFF5B3D58)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFFFD6F8)
internal val md_theme_dark_error = Color(0xFFFFB4AB)
internal val md_theme_dark_errorContainer = Color(0xFF93000A)
internal val md_theme_dark_onError = Color(0xFF690005)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_background = Color(0xFF000000)
internal val md_theme_dark_onBackground = Color(0xFFFFFFFF)
internal val md_theme_dark_surface = Color(0xFF1B1B1F)
internal val md_theme_dark_onSurface = Color(0xFFE4E2E6)
internal val md_theme_dark_surfaceVariant = Color(0xFF45464F)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFC5C6D0)
internal val md_theme_dark_outline = Color(0xFF8F909A)