name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set up TMDB API Key
      run: echo 'TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}' > ./local.properties

    - name: Build with Gradle
      run: ./gradlew build
